//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thinkgate.Portal.ParentStudent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.PropertyCollections = new HashSet<PropertyCollection>();
        }
    
        public int Id { get; set; }
        public string ClientID { get; set; }
        public string Environment { get; set; }
        public string State { get; set; }
    
        public virtual ICollection<PropertyCollection> PropertyCollections { get; set; }
    }
}
