//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thinkgate.Portal.ParentStudent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientSuppliedIdentification_LEA_Xref
    {
        public int ID { get; set; }
        public string ClientID { get; set; }
        public int ClientSuppliedIdentificationID { get; set; }
    }
}
