//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thinkgate.Portal.ParentStudent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyCollection
    {
        public PropertyCollection()
        {
            this.Properties = new HashSet<Property>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Client_Id { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ICollection<Property> Properties { get; set; }
    }
}
