//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessParentStudentImportWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int ID { get; set; }
        public Nullable<int> Page { get; set; }
        public string Student_Name { get; set; }
        public string Student_ID { get; set; }
        public Nullable<int> District { get; set; }
        public Nullable<int> School { get; set; }
        public string Grade { get; set; }
        public string Email { get; set; }
        public string LoginID { get; set; }
        public string Keywords { get; set; }
        public string Demo1 { get; set; }
        public string Demo2 { get; set; }
        public string Demo3 { get; set; }
        public string Demo4 { get; set; }
        public string Demo5 { get; set; }
        public string Demo6 { get; set; }
        public string Demo7 { get; set; }
        public string Email2 { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
        public string Student_State_ID { get; set; }
        public string Demo8 { get; set; }
        public string Demo9 { get; set; }
        public string Demo10 { get; set; }
        public string Picture { get; set; }
        public Nullable<System.Guid> aspnet_UsersID { get; set; }
    }
}
